services:
  webapp:
    image: cgr.dev/chainguard-private/aspnet-runtime-fips:8-dev
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=testdb;Username=testuser;Password=testpass;SslMode=Disable
    volumes:
      - ./publish:/app:ro
    working_dir: /app
    entrypoint: ["/usr/bin/dotnet", "AspMVC.dll"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: cgr.dev/chainguard-private/postgres:16-dev
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
